### ISSUE TITLE
TimeField erases seconds

### ISSUE THREAD

**Issue by patrickyan** [kvesteri/wtforms-components#48]
A time like 19:17:13 stored in the database gets displayed as 19:17 by TimeField, and saving the form erases the :13 from the database.

**Comment by tvuotila** [comment]
If the time is displayed as 19:17, it is same as 19:17:00. That gets saved to the database.
We should display the time as 19:17:13 which gets saved as such.

TimeField should allow setting format like `TimeField(format='%H:%M:%S')`.
Can you check if PR #49 fixes your problem? I have not yet resolved how to make the field format with step attribute like `<input type="time" name="time" step="1">`. The step attribute is needed in order to allow setting seconds.
